apiVersion: v1
kind: Service
metadata:
  name: my-sentiment-analysis-service
  labels:
    app: my-sentiment-analysis-api
spec:
  type: ClusterIP
  selector:
    app: my-sentiment-analysis-api
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8000