apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: my-sentiment-analysis-service    # scheint sich auf den Service zu bezieh _conf?
      port:
        number: 8001